version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017



  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"



  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
      - mongo
    command: >
      bash -c "
        pwd
        ls
        ls tests/
      "
    # command: >
    #   bash -c "
    #     pip install -r requirements-dev.txt &&
    #     pytest tests/ --junitxml=results.xml
    #   "
