version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mongo
    volumes:
      - ./app:/app
      - ./tests:/tests
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
