name: Tackle Mongo issue

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest  # MongoDB container
        ports:
          - 27017:27017     # Expose port 27017
        options: >-
          --health-cmd='curl --silent --fail mongodb://localhost:27017' 
          --health-interval=5s 
          --health-timeout=3s 
          --health-retries=5
