name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        # no healthcheck, keep it clean

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 27017 && echo "Mongo is up!" && exit 0
            echo "Waiting for Mongo..."
            sleep 2
          done
          echo "Mongo failed to start in time." && exit 1

      - name: Run tests
        run: |
          pytest -sv tests/ --junitxml=results.xml
      
      - name: Upload test results
        uses: actions/upload-artifact
        with:
          name: test-results
          path: results.xml