name: Run API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest  # Aligning with the Docker Compose version
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variable for MongoDB
        run: echo "MONGO_URI=mongodb://localhost:27017" >> $GITHUB_ENV

      - name: Run tests
        run: pytest --junitxml=results.xml

      # Uncomment this if you need to upload test results
      # - name: Upload test results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: test-results
      #     path: results.xml
